apiVersion: apps/v1
kind: Deployment
metadata:
  name: giants-backend
  namespace: giants-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giants-backend
  template:
    metadata:
      labels:
        app: giants-backend
    spec:
      containers:
        - name: giants-backend
          image: 711427856586.dkr.ecr.ap-northeast-1.amazonaws.com/giants-ecr-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: giants-config-backend
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: giants-config-backend
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: giants-config-backend
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: giants-secret-backend
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: giants-secret-backend
                  key: DB_PASSWORD