apiVersion: apps/v1
kind: Deployment
metadata:
  name: giants-frontend
  namespace: giants-sre
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giants-frontend
  template:
    metadata:
      labels:
        app: giants-frontend
    spec:
      containers:
        - name: giants-frontend
          image: 711427856586.dkr.ecr.ap-northeast-1.amazonaws.com/giants-sre-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://k8s-giantssr-sreportf-2d7a46bb7b-1433120804.ap-northeast-1.elb.amazonaws.com"