apiVersion: v1
kind: Service
metadata:
  name: giants-frontend-service
  namespace: giants-sre
spec:
  type: ClusterIP
  selector:
    app: giants-frontend
  ports:
    - port: 3000
      targetPort: 3000