apiVersion: v1
kind: Service
metadata:
  name: giants-service-frontend
  namespace: giants-namespace
spec:
  type: ClusterIP
  selector:
    app: giants-frontend
  ports:
    - port: 3000
      targetPort: 3000