deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: false

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1
    path_prefix: /tmp/loki

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage_config:
    filesystem:
      directory: /tmp/loki/chunks

  rulerConfig:
    storage:
      type: local
      local:
        directory: /tmp/loki/rules

chunksCache:
  enabled: false

resultsCache:
  enabled: false

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

gateway:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false