# name: Frontend CI/CD

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "frontend/**"
#       - "k8s/frontend/**"
#       - ".github/workflows/frontend.yml"

# env:
#   AWS_REGION: ap-northeast-1
#   FRONTEND_ECR_REPOSITORY: giants-ecr-frontend

# jobs:
#   frontend-build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Login to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Build and push frontend image
#         run: |
#           docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.FRONTEND_ECR_REPOSITORY }}:latest ./frontend
#           docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.FRONTEND_ECR_REPOSITORY }}:latest

#       - name: Update kubeconfig
#         run: |
#           aws eks update-kubeconfig \
#             --region ${{ env.AWS_REGION }} \
#             --name ${{ secrets.EKS_CLUSTER_NAME }}

#       - name: Restart frontend deployment
#         run: |
#           kubectl rollout restart deployment giants-deployment-frontend -n giants-namespace
#           kubectl rollout status deployment giants-deployment-frontend -n giants-namespace